openapi: 3.0.1
info:
  title: FoxTask
  description: 'Documentation for FoxTask - a simple and robust time management solution'
  version: 2.0.0
externalDocs:
  description: GitHub
  url: https://github.com/gnomedb/foxtask
servers:
- url: http://localhost:3000/api
tags:
- name: Auth
  description: Authentication
paths:
  /login:
    post:
      tags:
      - Login
      summary: Authenticate into the platform
      operationId: login
      requestBody:
        description: Login object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
        required: true
      responses:
        200:
          description: Successfully authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        401:
          description: Invalid username/password
          content: {}
  /signup:
    post:
      tags:
      - Signup
      summary: Register a user on the platform
      operationId: signup
      requestBody:
        description: Signup object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignup'
        required: true
      responses:
        200:
          description: Successfully registered user
          content: {}
        400:
          description: User already exists
          content: {}
  /me:
    get:
      tags:
      - Get user
      summary: Get authenticated user
      operationId: get_me
      parameters:
        - in: header
          name: Authorization
          schema:
            type: String
          required: true
          description: JWT Token
      responses:
        200:
          description: Successfully registered user
          content: {}
        400:
          description: User already exists
          content: {}
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        name:
          type: string
        password:
          type: string
      xml:
        name: User
    UserLogin:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    UserSignup:
      type: object
      properties:
        username:
          type: string
        name:
          type: string
          default: "Personal account"
        password:
          type: string
    TokenResponse:
      type: object
      properties:
        token:
          type: string
          description: "JWT Token"
