const Auth = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    SIGNUP: 'SIGNUP',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAIL: 'SIGNUP_FAIL',
    GET_USER: 'GET_USER',
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT'
};

export const Types = {
    Auth
};