const Auth = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    SIGNUP: 'SIGNUP',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAIL: 'SIGNUP_FAIL',
    GET_USER: 'GET_USER',
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT'
};

const Tasks = {
    GET_TASKS: 'GET_TASKS',
    GET_TASKS_FAIL: 'GET_TASKS_FAIL',
    SET_TASKS: 'SET_TASKS',
    CREATE_TASK: 'CREATE_TASK',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
    CREATE_TASK_FAIL: 'CREATE_TASK_FAIL'
}

export const Types = {
    Auth,
    Tasks
};